#to install packages delete "#"
#install.packages("tidyverse")
#install.packages("reshape2")
#install.packages("ISLR2")
#install.packages("readxl")
#install.packages("ggpubr")
#install.packages("viridis")
#install.packages("broom")

#load libraries
library(tidyverse)
library(reshape2)
library(readxl)
library(ggpubr)
library(viridis)
library(scales)
library(npreg)
library(broom)
library(knitr)

#load data 
data <- read.delim(file.choose()) 
data 

#group elution profiles of each condition by gene name
data_gr <- data %>%
  group_by(Condition) %>%
  pivot_longer(cols=3:37, names_to = "Fraction", values_to = "RelativeIntensity") %>% 
  rename("GeneID" = "Gene_names") %>%
  subset(., Condition != "SILAC")

data_gr$Fraction <- gsub("F","", as.character(data_gr$Fraction))

#create list of profiles grouped by gene name
uniq_prot = unique(data_gr$GeneID)
uniq_prot
#loop for profile plots of both conditions for each protein
for (i in uniq_prot) {
  temp_plot = ggplot(data= subset(data_gr, GeneID == i), aes(fct_inorder(Fraction), RelativeIntensity))  +
    geom_point(aes(group=Condition, color=Condition), size = 0.5) +
    geom_line(size=1.0, aes(group=Condition, color = Condition), alpha=0.6) +
    ggtitle(i) +
    scale_x_discrete(breaks = seq(1, 35, 2)) +
    scale_y_continuous(sec.axis = sec_axis(~./2, name = "SILAC ratio")) +
    scale_color_manual(values = c("#00FFFF", "#CC0066", "#003333")) +
    labs(x="Fraction",
         y="RelativeIntensity[%]") +
    theme(plot.title = element_text(vjust = -10,
                                    hjust = 0.02),
          legend.position = "none",
          text=element_text(size = 11, family = "Arial"),
          panel.grid = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank())
  
  ggsave(temp_plot, file=paste("GOBP_H2O2_plot_", i, ".png"), dpi = 1200,
         width = 14, height = 10, units = "cm")
}

while (!is.null(dev.list()))  dev.off()

# simulate replicates with 5% variance
var_sim <- seq(from= -5, to = 5, by = 0.1)

repVar <- seq(from = -0.05, to = 0.05, by = 0.001)
# muss auch replicate column erstellen!
# dplyr generatecolumn
# create function to simulate replicates with up to 5% variance
# simulateReps <-  function(df){
#   df %>% 
#     mutate(
#       rep2 = RelativeIntensity + 
#         (RelativeIntensity*sample(repVar, size = 35, replace = TRUE)),
#       rep3 = RelativeIntensity + 
#         (RelativeIntensity*sample(repVar, size = 35, replace = TRUE)))  %>% 
#     melt(., id = c("GeneID", "Condition", "Fraction")) %>% 
#     rename("Replicate" = "variable")  %>% 
#     rename("RelAbundance" = "value")  %>%
#     mutate(Replicate = recode(Replicate, RelativeIntensity = "1", rep2 = "2", rep3 = "3"))
#   
# }

replicateAll <- data_gr %>% 
  mutate(
    rep2 = RelativeIntensity + 
      (RelativeIntensity*sample(repVar, size = 98910, replace = TRUE)),
    rep3 = RelativeIntensity + 
      (RelativeIntensity*sample(repVar, size = 98910, replace = TRUE)))  %>% 
  melt(., id = c("GeneID", "Condition", "Fraction")) %>% 
  rename("Replicate" = "variable")  %>% 
  rename("RelAbundance" = "value")  %>%
  mutate(Replicate = recode(Replicate, RelativeIntensity = "1", rep2 = "2", rep3 = "3"))

# test <- replicateAll%>% 
#   subset(., GeneID == "LDHA")
# 
# testNull <- fitss(x = test)


LDHA <- data_gr %>% 
  subset(., GeneID == "LDHA") %>%
  mutate(
    rep2 = RelativeIntensity + 
      (RelativeIntensity*sample(repVar, size = 35, replace = TRUE)),
    rep3 = RelativeIntensity + 
      (RelativeIntensity*sample(repVar, size = 35, replace = TRUE)))  %>% 
  melt(., id = c("GeneID", "Condition", "Fraction")) %>% 
  rename("Replicate" = "variable")  %>% 
  rename("RelAbundance" = "value")  %>%
  mutate(Replicate = recode(Replicate, RelativeIntensity = "1", rep2 = "2", rep3 = "3"))
 


# plot simulated data
rep_plot = ggplot(data= LDHA,
                  aes(x = fct_inorder(Fraction),y = RelAbundance)) + 
  geom_point(aes(color = Condition, shape = Replicate),
             position = position_dodge(width=0.4), size = 2) +
  ggtitle("LDHA") +
  scale_x_discrete(breaks = seq(1, 35, 2)) +
  labs(x="Fraction",
       y="Relative Abundance [%]") +
  theme_bw()

print(rep_plot)

# create function to generate smoothing spline
fitss <-  function(x){
  with(x, ss(Fraction, RelAbundance,
              all.knots = TRUE,
              keep.data = TRUE))
}

# The generated smoothing function is applied to generate the null model.
nullfit <- fitss(x = LDHA_simba)

# The predictions and residuals generated by the model are saved in a nested list.
# We will extract these parameters and append them to our data.
LDHA_fit <- LDHA %>%
  add_column(nullResiduals = residuals.ss(nullfit)) %>%
  add_column(nullPredicted = fitted.ss(nullfit))

sum(residuals.ss(nullfit)^2)
plot.ss(LDHA_fit)
# Now we can plot the fitted null model to the data.
LDHA_plot <- rep_plot +
  geom_line(data = LDHA_fit, aes(y = nullPredicted, group = 1), size = 1)

print(LDHA_plot)

LDHA_nullRes <- rep_plot +
 geom_line(aes(group = Replicate),
            linetype = "dotted", size=0.6, alpha=1) +
 geom_line(data = LDHA_fit, aes(y = nullPredicted, group = 1), size = 1)
  
print(LDHA_nullRes)
# For the alternative model we group the replicate data by condition and fit the alternative model for each condition separately.

LDHA_alt2 <- LDHA_simba %>%
  group_by(Condition) %>%
  do(fitss(x = .)) %>%
  ungroup(.)

altfit_c <- data.frame(Fraction = as.character(LDHA_alt[[2]][[1]]$data$x),
                           RelAbundance = LDHA_alt[[2]][[1]]$data$y,
                           altResiduals = residuals.ss(LDHA_alt[[2]][[1]]),
                           altPredicted = fitted.ss(LDHA_alt[[2]][[1]]),
                       Condition = "Ctrl",
                       Replicate = as.character(rep(c(1,2,3), each=35)))

altfit_i <- data.frame(Fraction = as.character(LDHA_alt[[2]][[2]]$data$x),
                       RelAbundance = LDHA_alt[[2]][[2]]$data$y,
                       altResiduals = residuals.ss(LDHA_alt[[2]][[2]]),
                       altPredicted = fitted.ss(LDHA_alt[[2]][[2]]),
                       Condition = "IBR",
                       Replicate = as.character(rep(c(1,2,3), each=35)))

# Join predicted values and residuals from both models and append to the original data.
LDHAAltPar <- rbind(altfit_c, altfit_i)

LDHA_fit <- LDHA_fit %>%
  left_join(LDHAAltPar, 
            by = c("RelAbundance", "Fraction", 
                   "Condition", "Replicate")) %>%
  distinct()


# Next we can plot null and alternative models.
LDHA_plot <- LDHA_plot +
  geom_line(data = distinct(LDHA_fit, Fraction, Condition, altPredicted, .keep_all = FALSE),
            aes(y = altPredicted, group = Condition, color = Condition),
            size = 1)

print(LDHA_plot)

# In order to quantify the differences in goodness-of-fit between the models we will calculate the sum of squared residuals.
rss_LDHA <- LDHA_fit %>%
  summarise(rssNUll = sum(nullResiduals^2),
            rssAlt = sum(altResiduals^2))

kable(rss_LDHA, digits = 3)

DOF_null <- nullfit$df 

DOF_alt <- 


# In order to expand the model to the whole data set, we need to write a function
# which simulates technical replicates. Here we choose variance of up to +/- 5%. 

repVar <- seq(from = -0.05, to = 0.05, by = 0.001)

simulateReps <-  function(df){
  df %>% 
    mutate(
      factor2 = sample(repVar, size = 70, replace = TRUE),
      rep2 = RelativeIntensity + 
        (RelativeIntensity*factor2),
      factor3 = sample(repVar, size = 70, replace = TRUE),
      rep3 = RelativeIntensity + 
        (RelativeIntensity*factor3)) %>%
    subset(., select = -c(5,7)) %>% 
    melt(., id = c("GeneID", "Condition", "Fraction")) %>% 
    rename("Replicate" = "variable")  %>% 
    rename("RelAbundance" = "value")  %>%
    mutate(Replicate = recode(Replicate, RelativeIntensity = "1", rep2 = "2", rep3 = "3"))
}

# Next we will applz both of our functions to all quantified proteins.


test <- data_gr %>% 
  subset(., GeneID == "LDHA") %>%
  do(
    simulateReps(.),
    fitss(.))  
  
  
  

#plot smooth functions
smoothctrl_plot = ggplot(data= subset(LDHA_simba, Condition == "Ctrl"),
                         aes(fct_inorder(Fraction),value)) + 
  geom_point(aes(group=Condition, shape=Experiment), 
             fill="black", color= "black", size = 2) +
  geom_line(aes(group=Experiment), color= "black", linetype = "dotted",
            alpha=0.3, size=0.1) +
  stat_smooth(method = "loess", formula = y ~ x,
              aes(group=Condition, color="smooth function"),  
              linetype = 0, size = 0,
              span = 0.1, se= TRUE, show.legend = FALSE) +
  stat_smooth(method = "loess", formula = y ~ x, 
              aes(group=Condition, color="smooth function"),
              alpha = 0.4, color = alpha("#00FFFF", .4),
              size = 2, span = 0.1, se = FALSE) +
  scale_x_discrete(breaks = seq(1, 35, 2)) +
  labs(x="Fraction",
       y="Relative Intensity [%]") +
  theme(plot.title = element_text(vjust = -10,
                                  hjust = 0.02,
                                  size = 14),
        legend.position = c(0.8, 0.5),
        legend.key.size = unit(2, "cm"),
        legend.key = element_rect(fill = NA),
        legend.box.background = element_rect(color="black", size = 1),
        legend.box.margin = margin(3,3,3,3),
        legend.text = element_text(size = 9,
        ),
        legend.title = element_blank(),
        text=element_text(size = 9, 
                          family = "Arial", 
                          face = "bold"),
        panel.grid = element_blank(),
        panel.background = element_blank()) +
  guides(color=guide_legend(override.aes = list(fill=NA)))

smoothctrl_plot



smoothIBR_plot = ggplot(data= subset(LDHA_simba, Condition == "IBR"),
                         aes(fct_inorder(Fraction),value)) + 
  geom_point(aes(group=Condition, shape=Experiment), 
             fill="black", color= "black", size = 2) +
  geom_line(aes(group=Experiment), color= "black", linetype = "dotted",
            alpha=0.3, size=0.1) +
  stat_smooth(method = "loess", formula = y ~ x,
              aes(group=Condition, color="smooth function"),  
              linetype = 0, size = 0,
              span = 0.1, se= TRUE, show.legend = FALSE) +
  stat_smooth(method = "loess", formula = y ~ x, 
              aes(group=Condition, color="smooth function"),
              alpha = 0.4, color = alpha("#CC0066", .4),
              size = 2, span = 0.1, se = FALSE) +
  scale_x_discrete(breaks = seq(1, 35, 2)) +
  labs(x="Fraction",
       y="Relative Intensity [%]") +
  theme(plot.title = element_text(vjust = -10,
                                  hjust = 0.02,
                                  size = 14),
        legend.position = c(0.8, 0.5),
        legend.key.size = unit(2, "cm"),
        legend.key = element_rect(fill = NA),
        legend.box.background = element_rect(color="black", 
                                             size = 1),
        legend.box.margin = margin(3,3,3,3),
        legend.text = element_text(size = 9,
                                   ),
        legend.title = element_blank(),
        text=element_text(size = 9, 
                          family = "Arial",
                          face = "bold"),
        panel.grid = element_blank(),
        panel.background = element_blank()) +
  guides(color=guide_legend(override.aes = list(fill=NA)))

smoothIBR_plot


#merge smooth functions

smooth_plot = ggplot(data= subset(LDHA_simba, 
                                  Experiment == "Ctrl rep1" |Experiment  == "IBR rep1"),
                     aes(fct_inorder(Fraction),value)) +
  geom_line(aes(group = Fraction), linetype = 3, size = 1) +
  stat_smooth(method = "loess", formula = y ~ x,
              aes(group=Condition, color=Condition),  
              linetype = 0, size = 0,
              span = 0.1, se= TRUE, show.legend = FALSE) +
  stat_smooth(method = "loess", formula = y ~ x, 
              aes(group=Condition, color=Condition),
              size = 2, span = 0.1, se = FALSE) +
  scale_color_manual(values = c("#00FFFF", "#CC0066", "#003333"))+
  scale_x_discrete(breaks = seq(1, 35, 2)) +
  labs(x="Fraction",
       y="Relative Intensity [%]") +
  theme(plot.title = element_text(vjust = -10,
                                  hjust = 0.02,
                                  size = 14),
        legend.position = c(0.8, 0.8),
        legend.key.size = unit(1, "cm"),
        legend.key = element_rect(fill = NA),
        legend.box.background = element_rect(color="black", size = 1),
        legend.box.margin = margin(3,3,3,3),
        legend.text = element_text(size = 10),
        text=element_text(size = 9, 
                          family = "Arial",
                          face = "bold"),
        panel.grid = element_blank(),
        panel.background = element_blank()) +
  guides(color=guide_legend(override.aes = list(fill=NA)))

smooth_plot


#arrange grid
smooth_grid <- ggarrange(repctrl_plot, smoothctrl_plot, smooth_plot, 
                       repIBR_plot, smoothIBR_plot, ncol = 3, nrow = 2,
                       common.legend = TRUE, legend = "bottom",
                       labels = c("A", "B", "C"))
print(smooth_grid)

ggsave(prob_grid, file=paste("smoothing_principle.png"), dpi = 1200,
       width = 14, height = 10, units = "cm")

refsmooth_plot = ggplot(data= subset(LDHA_simba, 
                                     Experiment == "Ctrl rep1" |Experiment  == "IBR rep1"),
                     aes(fct_inorder(Fraction),value)) +
  geom_point(aes(shape = Experiment, color = Condition), size = 2) +
  stat_smooth(method = "loess", formula = y ~ x,
              linetype = 1, size = 2,
              span = 0.1, se= TRUE, show.legend = FALSE) +
  stat_smooth(method = "loess", formula = y ~ x, 
              size = 2, span = 0.1, se = FALSE) +
  scale_x_discrete(breaks = seq(1, 35, 2)) +
  labs(x="Fraction",
       y="Relative Intensity [%]") +
  theme(plot.title = element_text(vjust = -10,
                                  hjust = 0.02,
                                  size = 14),
        legend.position = c(0.8, 0.8),
        legend.key.size = unit(1, "cm"),
        legend.key = element_rect(fill = NA),
        legend.box.background = element_rect(color="black", size = 1),
        legend.box.margin = margin(3,3,3,3),
        legend.text = element_text(size = 10),
        text=element_text(size = 9, 
                          family = "Arial",
                          face = "bold"),
        panel.grid = element_blank(),
        panel.background = element_blank()) +
  guides(color=guide_legend(override.aes = list(fill=NA)))

refsmooth_plot

scale_color_manual(values = c("#00FFFF", "#CC0066", "#003333"))+

  
LDHA_c1 <- LDHA_simba %>%
  subset(., Experiment == "Ctrl rep1")

LDHA_c <- LDHA_simba %>%
  subset(., Condition == "Ctrl")
LDHA_i <- LDHA_simba %>%
  subset(., Condition == "IBR")


mod.ss.merged <- with(LDHA_simba, ss(Fraction, value, all.knots = TRUE, keep.data = TRUE))
mod.ss.merged
summary(mod.ss.merged)

  






nullPrediction <- LDHA_simba %>%
  group_by(Condition) %>%
  do({
    fit = fitss(.)
  }) %>%

# calculate sum of squared residuals

  
# extract degrees of freedom from fitted model
  
# 
  
# create function to extract residuals and fitted data 
# exRegStat <- function(ID){
#   =data.frame()
# }

plot(mod.ss.merged, xlab = "Fraction", ylab = "Intensity")

mod.ss.ibr <- with(LDHA_i, ss(Fraction, value, nknots = 34))
mod.ss.ibr
summary(mod.ss.ibr)
plot(mod.ss.ibr, xlab = "Fraction", ylab = "Intensity")
mod.ss.ibr$df

LDHA_cx <- left_join(LDHA_i, mod.ss.ibr$data, by=c("Fraction"="x"))
  
h0pred <- mod.ss.merged$data

mod.ss.ibr2 <- with(LDHA_i, ss(Fraction, value, all.knots = TRUE, keep.data = TRUE))
summary(mod.ss.ibr2)

